update=2020/01/11 11:21:09
version=1
last_client=eeschema
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=C:/Users/takumi/Documents/Kicad/library/library/74xgxx
LibName2=C:/Users/takumi/Documents/Kicad/library/library/74xx
LibName3=C:/Users/takumi/Documents/Kicad/library/library/ac-dc
LibName4=C:/Users/takumi/Documents/Kicad/library/library/adc-dac
LibName5=C:/Users/takumi/Documents/Kicad/library/library/adm3054
LibName6=C:/Users/takumi/Documents/Kicad/library/library/analog_switches
LibName7=C:/Users/takumi/Documents/Kicad/library/library/arduino
LibName8=C:/Users/takumi/Documents/Kicad/library/library/atmel
LibName9=C:/Users/takumi/Documents/Kicad/library/library/audio
LibName10=C:/Users/takumi/Documents/Kicad/library/library/brooktre
LibName11=C:/Users/takumi/Documents/Kicad/library/library/cmos_ieee
LibName12=C:/Users/takumi/Documents/Kicad/library/library/cmos4000
LibName13=C:/Users/takumi/Documents/Kicad/library/library/conn
LibName14=C:/Users/takumi/Documents/Kicad/library/library/contrib
LibName15=C:/Users/takumi/Documents/Kicad/library/library/cypress
LibName16=C:/Users/takumi/Documents/Kicad/library/library/dc-dc
LibName17=C:/Users/takumi/Documents/Kicad/library/library/device
LibName18=C:/Users/takumi/Documents/Kicad/library/library/digital-audio
LibName19=C:/Users/takumi/Documents/Kicad/library/library/display
LibName20=C:/Users/takumi/Documents/Kicad/library/library/dsp
LibName21=C:/Users/takumi/Documents/Kicad/library/library/elec-unifil
LibName22=C:/Users/takumi/Documents/Kicad/library/library/ftdi
LibName23=C:/Users/takumi/Documents/Kicad/library/library/gennum
LibName24=C:/Users/takumi/Documents/Kicad/library/library/graphic
LibName25=C:/Users/takumi/Documents/Kicad/library/library/intel
LibName26=C:/Users/takumi/Documents/Kicad/library/library/interface
LibName27=C:/Users/takumi/Documents/Kicad/library/library/leds
LibName28=C:/Users/takumi/Documents/Kicad/library/library/linear
LibName29=C:/Users/takumi/Documents/Kicad/library/library/logo
LibName30=C:/Users/takumi/Documents/Kicad/library/library/memory
LibName31=C:/Users/takumi/Documents/Kicad/library/library/microchip
LibName32=C:/Users/takumi/Documents/Kicad/library/library/microchip_pic10mcu
LibName33=C:/Users/takumi/Documents/Kicad/library/library/microchip_pic12mcu
LibName34=C:/Users/takumi/Documents/Kicad/library/library/microchip_pic16mcu
LibName35=C:/Users/takumi/Documents/Kicad/library/library/microchip1
LibName36=C:/Users/takumi/Documents/Kicad/library/library/microcontrollers
LibName37=C:/Users/takumi/Documents/Kicad/library/library/motorola
LibName38=C:/Users/takumi/Documents/Kicad/library/library/msp430
LibName39=C:/Users/takumi/Documents/Kicad/library/library/myDevice
LibName40=C:/Users/takumi/Documents/Kicad/library/library/myPic
LibName41=C:/Users/takumi/Documents/Kicad/library/library/myRelay
LibName42=C:/Users/takumi/Documents/Kicad/library/library/nxp_armmcu
LibName43=C:/Users/takumi/Documents/Kicad/library/library/opto
LibName44=C:/Users/takumi/Documents/Kicad/library/library/philips
LibName45=C:/Users/takumi/Documents/Kicad/library/library/pic24fjxxgb
LibName46=C:/Users/takumi/Documents/Kicad/library/library/power
LibName47=C:/Users/takumi/Documents/Kicad/library/library/powerint
LibName48=C:/Users/takumi/Documents/Kicad/library/library/pspice
LibName49=C:/Users/takumi/Documents/Kicad/library/library/references
LibName50=C:/Users/takumi/Documents/Kicad/library/library/regul
LibName51=C:/Users/takumi/Documents/Kicad/library/library/relays
LibName52=C:/Users/takumi/Documents/Kicad/library/library/sensors
LibName53=C:/Users/takumi/Documents/Kicad/library/library/siliconi
LibName54=C:/Users/takumi/Documents/Kicad/library/library/special
LibName55=C:/Users/takumi/Documents/Kicad/library/library/stm8
LibName56=C:/Users/takumi/Documents/Kicad/library/library/stm32
LibName57=C:/Users/takumi/Documents/Kicad/library/library/STM32F103_48
LibName58=C:/Users/takumi/Documents/Kicad/library/library/supertex
LibName59=C:/Users/takumi/Documents/Kicad/library/library/texas
LibName60=C:/Users/takumi/Documents/Kicad/library/library/transf
LibName61=C:/Users/takumi/Documents/Kicad/library/library/transistors
LibName62=C:/Users/takumi/Documents/Kicad/library/library/ttl_ieee
LibName63=C:/Users/takumi/Documents/Kicad/library/library/user
LibName64=C:/Users/takumi/Documents/Kicad/library/library/valves
LibName65=C:/Users/takumi/Documents/Kicad/library/library/video
LibName66=C:/Users/takumi/Documents/Kicad/library/library/volumes
LibName67=C:/Users/takumi/Documents/Kicad/library/library/xilinx
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=stm32f4_board_test.net
CopperLayerCount=4
BoardThickness=1.6
AllowMicroVias=0
AllowBlindVias=0
RequireCourtyardDefinitions=0
ProhibitOverlappingCourtyards=1
MinTrackWidth=0.2
MinViaDiameter=0.5
MinViaDrill=0.3
MinMicroViaDiameter=0.2
MinMicroViaDrill=0.09999999999999999
MinHoleToHole=0.25
TrackWidth1=0.25
TrackWidth2=0.25
TrackWidth3=0.35
TrackWidth4=0.5
TrackWidth5=0.8
TrackWidth6=0.9
TrackWidth7=1
ViaDiameter1=0.6
ViaDrill1=0.4
ViaDiameter2=0.5
ViaDrill2=0.3
ViaDiameter3=0.5
ViaDrill3=0.3
ViaDiameter4=0.8
ViaDrill4=0.5
ViaDiameter5=6
ViaDrill5=3
dPairWidth1=0.2
dPairGap1=0.25
dPairViaGap1=0.25
SilkLineWidth=0.15
SilkTextSizeV=1
SilkTextSizeH=1
SilkTextSizeThickness=0.15
SilkTextItalic=0
SilkTextUpright=1
CopperLineWidth=0.2
CopperTextSizeV=1.5
CopperTextSizeH=1.5
CopperTextThickness=0.3
CopperTextItalic=0
CopperTextUpright=1
EdgeCutLineWidth=0.15
CourtyardLineWidth=0.05
OthersLineWidth=0.15
OthersTextSizeV=1
OthersTextSizeH=1
OthersTextSizeThickness=0.15
OthersTextItalic=0
OthersTextUpright=1
SolderMaskClearance=0.2
SolderMaskMinWidth=0
SolderPasteClearance=0
SolderPasteRatio=0
[pcbnew/Layer.F.Cu]
Name=F.Cu
Type=0
Enabled=1
[pcbnew/Layer.In1.Cu]
Name=In1.Cu
Type=1
Enabled=1
[pcbnew/Layer.In2.Cu]
Name=In2.Cu
Type=1
Enabled=1
[pcbnew/Layer.In3.Cu]
Name=In3.Cu
Type=0
Enabled=0
[pcbnew/Layer.In4.Cu]
Name=In4.Cu
Type=0
Enabled=0
[pcbnew/Layer.In5.Cu]
Name=In5.Cu
Type=0
Enabled=0
[pcbnew/Layer.In6.Cu]
Name=In6.Cu
Type=0
Enabled=0
[pcbnew/Layer.In7.Cu]
Name=In7.Cu
Type=0
Enabled=0
[pcbnew/Layer.In8.Cu]
Name=In8.Cu
Type=0
Enabled=0
[pcbnew/Layer.In9.Cu]
Name=In9.Cu
Type=0
Enabled=0
[pcbnew/Layer.In10.Cu]
Name=In10.Cu
Type=0
Enabled=0
[pcbnew/Layer.In11.Cu]
Name=In11.Cu
Type=0
Enabled=0
[pcbnew/Layer.In12.Cu]
Name=In12.Cu
Type=0
Enabled=0
[pcbnew/Layer.In13.Cu]
Name=In13.Cu
Type=0
Enabled=0
[pcbnew/Layer.In14.Cu]
Name=In14.Cu
Type=0
Enabled=0
[pcbnew/Layer.In15.Cu]
Name=In15.Cu
Type=0
Enabled=0
[pcbnew/Layer.In16.Cu]
Name=In16.Cu
Type=0
Enabled=0
[pcbnew/Layer.In17.Cu]
Name=In17.Cu
Type=0
Enabled=0
[pcbnew/Layer.In18.Cu]
Name=In18.Cu
Type=0
Enabled=0
[pcbnew/Layer.In19.Cu]
Name=In19.Cu
Type=0
Enabled=0
[pcbnew/Layer.In20.Cu]
Name=In20.Cu
Type=0
Enabled=0
[pcbnew/Layer.In21.Cu]
Name=In21.Cu
Type=0
Enabled=0
[pcbnew/Layer.In22.Cu]
Name=In22.Cu
Type=0
Enabled=0
[pcbnew/Layer.In23.Cu]
Name=In23.Cu
Type=0
Enabled=0
[pcbnew/Layer.In24.Cu]
Name=In24.Cu
Type=0
Enabled=0
[pcbnew/Layer.In25.Cu]
Name=In25.Cu
Type=0
Enabled=0
[pcbnew/Layer.In26.Cu]
Name=In26.Cu
Type=0
Enabled=0
[pcbnew/Layer.In27.Cu]
Name=In27.Cu
Type=0
Enabled=0
[pcbnew/Layer.In28.Cu]
Name=In28.Cu
Type=0
Enabled=0
[pcbnew/Layer.In29.Cu]
Name=In29.Cu
Type=0
Enabled=0
[pcbnew/Layer.In30.Cu]
Name=In30.Cu
Type=0
Enabled=0
[pcbnew/Layer.B.Cu]
Name=B.Cu
Type=0
Enabled=1
[pcbnew/Layer.B.Adhes]
Enabled=1
[pcbnew/Layer.F.Adhes]
Enabled=1
[pcbnew/Layer.B.Paste]
Enabled=1
[pcbnew/Layer.F.Paste]
Enabled=1
[pcbnew/Layer.B.SilkS]
Enabled=1
[pcbnew/Layer.F.SilkS]
Enabled=1
[pcbnew/Layer.B.Mask]
Enabled=1
[pcbnew/Layer.F.Mask]
Enabled=1
[pcbnew/Layer.Dwgs.User]
Enabled=1
[pcbnew/Layer.Cmts.User]
Enabled=1
[pcbnew/Layer.Eco1.User]
Enabled=1
[pcbnew/Layer.Eco2.User]
Enabled=1
[pcbnew/Layer.Edge.Cuts]
Enabled=1
[pcbnew/Layer.Margin]
Enabled=1
[pcbnew/Layer.B.CrtYd]
Enabled=1
[pcbnew/Layer.F.CrtYd]
Enabled=1
[pcbnew/Layer.B.Fab]
Enabled=1
[pcbnew/Layer.F.Fab]
Enabled=1
[pcbnew/Layer.Rescue]
Enabled=0
[pcbnew/Netclasses]
[pcbnew/Netclasses/Default]
Name=Default
Clearance=0.15
TrackWidth=0.25
ViaDiameter=0.6
ViaDrill=0.4
uViaDiameter=0.3
uViaDrill=0.1
dPairWidth=0.2
dPairGap=0.25
dPairViaGap=0.25
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=C:/Users/81906/Documents/Datasheets/回路図/
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceAjustPassiveValues=0
LabSize=50
ERC_TestSimilarLabels=1
